events {}

http {
	server {
		listen 8002;
		server_name localhost;	
		
		location /tarefas {
			proxy_pass http://tarefas:8000;

			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header Host $host;
		}

		location /notificar {
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			
			proxy_pass http://notificacoes:8001;
		}
	}
}