name: 'Pipeline 04/07/26'

on:
  #Habilita botão na interface Web para acionar manualmente a pipeline
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  integracao:
    name: 'Integração'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Instalação de Dependências'
        run: pip install -r requiriments.txt
      - name: 'Testes unitários'
        run: pytest 
      - name: 'Cobertura de Código'
        run: pytest --cov --cov-fail-under=80
      - name: 'Análise estática'
        run : bandit -r app/
      - name: 'Linting'
        run : pylint app/ || true